#!/bin/bash
#SBATCH --job-name=rns_test           
#SBATCH --partition=short
## SBATCH --nodes=1                  
#SBATCH --ntasks=128               
#SBATCH --cpus-per-task=4             
##SBATCH --time=10:00:00               
#SBATCH --output=rns_test_%j.out      
#SBATCH --error=rns_test_%j.err       

# 1. Load the OpenMPI environment
module purge
module load mpi/openmpi/4.1.8-gcc

# 2. Tell the system where your custom HDF5 library lives
export LD_LIBRARY_PATH=/home/mi58rip/local/hdf5/lib:$LD_LIBRARY_PATH

# 3. Create a clean folder for the simulation data
rm -rf outputs/test_SMR
rm -rf RNS_DATA
mkdir -p outputs/test_SMR

# 4. Run the code!
# mpirun -n $SLURM_NTASKS -- stdbuf -o0 -e0 $HOME/gr-athena/bin/athena_rns_SFHo -i gr_rns_input_SFHo.par -d outputs/test_SMR
mpirun --mca btl_openib_allow_ib true --mca btl_openib_want_fork_guard 1 -n $SLURM_NTASKS -- stdbuf -o0 -e0 $HOME/gr-athena/bin/athena_rns_SFHo -i gr_rns_input_SFHo.par -d outputs/test_SMR

# command for restarting
# NEW_TLIM=2030.4
# RESTART_FILE="outputs/test_SMR/gr_rns.final.rst"

# mpirun --mca btl_openib_allow_ib true --mca btl_openib_want_fork_guard 1 -n $SLURM_NTASKS -- stdbuf -o0 -e0 $HOME/gr-athena/bin/athena_rns_SFHo -r $RESTART_FILE -d outputs/test_SMR time/tlim=$NEW_TLIM