#!/bin/bash
#SBATCH --job-name=plotting           
#SBATCH --partition=long               
#SBATCH --ntasks=1             
#SBATCH --cpus-per-task=4   
#SBATCH --mem=128G         
##SBATCH --output=plotting_%j.out      
##SBATCH --error=plotting_%j.err       

# 1. Load the OpenMPI environment
# module purge

# eval "$(mamba shell.bash hook)"
# mamba activate grathena_python

/cluster/spack/opt/spack/linux-almalinux8-zen/gcc-8.3.1/python-3.8.6-3rggdkkl5u7llkowgbooapfr4ft7vvln/bin/python /home/mi58rip/gr-athena/py_scripts/plotting_scripts/plotting_diagnostics_aic.py