#!/bin/bash
#SBATCH --job-name=aic_test           
#SBATCH --partition=short               
#SBATCH --ntasks=288          
#SBATCH --cpus-per-task=2            
##SBATCH --time=10:00:00                
#SBATCH --output=aic_test_%j.out      
#SBATCH --error=aic_test_%j.err       

# 1. Load the OpenMPI environment
module purge
module load mpi/openmpi/4.1.8-gcc

# 2. Tell the system where your custom libraries live
export LD_LIBRARY_PATH=/home/mi58rip/local/hdf5/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH="/home/mi58rip/rnsc/lib:$LD_LIBRARY_PATH"

#RESTART_FILE="/home/mi58rip/gr-athena/runs/aic_SFHo_64_64_64/output-0000/aic.00020.rst"
RESTART_FILE="/home/mi58rip/gr-athena/runs/aic_SFHo_64_64_64/test_rewrite_ID_AMR/aic.00039.rst"
# 3. High-speed InfiniBand network
export OMPI_MCA_btl_openib_allow_ib=true
export OMPI_MCA_btl_openib_want_fork_guard=1

# 4. HDF5 bypasses
#export HDF5_USE_FILE_LOCKING=FALSE
#export OMPI_MCA_io_ompio_enable_mca_coll=0

# 5. THE BEEGFS FIX: Ban OpenMPI from creating shared file pointer lock files
#export OMPI_MCA_sharedfp="^lockedfile"

# 6. Thread Pinning
#export OMP_PROC_BIND=true
#export OMP_PLACES=cores
#export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

# 7. Native SLURM launch
srun -n $SLURM_NTASKS $HOME/gr-athena/bin/athena_aic -r $RESTART_FILE -d . mesh/numlevel=12 problem/delta_max_m=0.000125 problem/detect_bounce=false problem/equilibriate_post_bounce=false
#srun -n $SLURM_NTASKS $HOME/gr-athena/bin/athena_aic -i parfile.t -d .
